$:.unshift "#{File.dirname(__FILE__)}/lib/builders"
  require "creator"
  require "flight_creator"
  require "plane_creator"
  
$:.unshift "#{File.dirname(__FILE__)}/lib/mapping_and_routing"
  require "airport_map"
  require "flight_map"
  require "flight_plan"
  require "flight_segment"
  require "map_marker"
  require "map_path"
  require "segment_series"
  require "static_map"
  
$:.unshift "#{File.dirname(__FILE__)}/lib/other"
  require "fly_error"
  require "query_collection"
  require "query_collection_exclusive_key"
  require "query_collection_non_exclusive_key"
  require "query_param"

$:.unshift "#{File.dirname(__FILE__)}/lib/quantities"
  require "distance_in_miles"
  require "duration_in_seconds"
  require "number_of_passengers"
  require "quantity"
  require "starting_miles_count"
  require "starting_pax_count"